name: markdown lint

on: [push, pull_request]

jobs: # Docs: <https://help.github.com/en/articles/workflow-syntax-for-github-actions>
  lint-changelog:
    name: markdown lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master

      - name: Install markdown lint cli
        run: npm install -g markdownlint-cli

      - name: Lint markdown file
        run: markdownlint-cli -f *.md